version: '3.7'

networks:
  traefik:
    external:
      name: traefik
  blog_tp_backend: ~

volumes:
  wp-data: ~

services:
  db:
    image: mysql:5.7
    container_name: tpblog_db
    volumes:
      - ./data/db:/var/lib/mysql/
      - ./data/mysql_init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - blog_tp_backend

  wp:
    build:
      context: data/docker/wordpress
    image: tp-wordpress:1.0
    container_name: tpblog_wp
    env_file:
      - .env
    volumes:
      - ./content:/var/www/html/wp-content
      - wp-data:/var/www/html
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:blog.talentplatforms.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.backend=blog_tp"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - blog_tp_backend
      - traefik

  # helper container!
  # this one is allowed to exit after it's done
  composer:
    build:
      context: data/docker/composer
    image: wp-composer:1.0
    container_name: tpblog_composer
    command: composer install -n
    volumes:
      - .:/app

  # helper container!
  # this one is allowed to exit after it's done
  wp_cli:
    build:
      context: data/docker/wp-cli
    container_name: tpblog__wp_cli
    image: wp-cli:1.0
    entrypoint: /app/start.sh
    depends_on:
      - db
      - wp
    env_file:
      - .env
    volumes:
      - wp-data:/var/www/html
    networks:
      - blog_tp_backend

  # webpack:
  #   build:
  #     context: data/docker/webpack
  #   container_name: tpblog_webpack
  #   depends_on:
  #     - wp
  #   restart: always
  #   # volumes:
  #     # - ./data/tpde-theme:/home/node/app
  #   environment:
  #     NODE_ENV: development
