version: '3.7'

networks:
  traefik:
    external:
      name: traefik
  your_wp_backend: ~

volumes:
  composer-cache: ~

services:
  db:
    image: mysql:5.7
    container_name: tpblog_db
    volumes:
      - ./data/db:/var/lib/mysql/
      # mounts an initial mysql state
      # https://hub.docker.com/_/mysql section: Initializing a fresh instance
      - ./data/mysql_init:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "3306:3306"
    networks:
      - your_wp_backend

  wp:
    build:
      context: data/docker/wordpress
    image: your-wordpress:1.0 # change accordingly to project name
    container_name: your_wp
    entrypoint: bash -c '/app/build.sh && /app/start.sh'
    env_file:
      - .env
    volumes:
      - composer-cache:/root/.composer
      - ./app:/app/wp:cached
      - ./composer.local.json:/app/composer.local.json:ro
      # - ./theme:/app/wp/wp-content/theme/my-theme-name # create folder on host and put stuff in there
      # - ./plugin:/app/wp/wp-content/plugin/my-plugin # create folder on host and put stuff in there
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:your.wp.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik"
      - "traefik.backend=your_wp"
      - "traefik.frontend.entryPoints=http,https"
    networks:
      - your_wp_backend
      - traefik

  # webpack:
  #   build:
  #     context: data/docker/webpack
  #   container_name: tpblog_webpack
  #   depends_on:
  #     - wp
  #   restart: always
  #   # volumes:
  #     # - ./theme:/home/node/app
  #   environment:
  #     NODE_ENV: development
