<?php
/**
 * Configures wordpress
 * !! AUTOGENERATED !!
 */

// Absolute path to the wordpress directory.
if (!defined('ABSPATH')) {
    define('ABSPATH', dirname(__FILE__) . '/');
}

ini_set('html_errors', getenv('WORDPRESS_HTML_ERRORS'));
$wp_home = getenv('WORDPRESS_HOME');
$table_prefix = getenv('WORDPRESS_TABLE_PREFIX');

define('DB_NAME', getenv('WORDPRESS_DB_NAME'));
define('DB_USER', getenv('WORDPRESS_DB_USER'));
define('DB_PASSWORD', getenv('WORDPRESS_DB_PASSWORD'));
define('DB_HOST', getenv('WORDPRESS_DB_HOST'));
define('DB_CHARSET', 'utf8');
define('DB_COLLATE', 'utf8_general_ci');

// NO Theme or Plugin Editor
define('DISALLOW_FILE_EDIT', true);
define('WP_POST_REVISIONS', 5);
define('EMPTY_TRASH_DAYS', 28);

define('WPLANG', getenv('WORDPRESS_LANG'));
define('WP_DEBUG', getenv('WORDPRESS_DEBUG'));
define('WP_AUTO_UPDATE_CORE', getenv('WORDPRESS_AUTO_UPDATE_CORE'));

define('WP_HOME', $wp_home);
define('WP_SITEURL', $wp_home);

// https://codex.wordpress.org/Administration_Over_SSL
define('FORCE_SSL_ADMIN', true);
// in some setups HTTP_X_FORWARDED_PROTO might contain
// a comma-separated list e.g. http,https
// so check for https existence
if (strpos($_SERVER['HTTP_X_FORWARDED_PROTO'], 'https') !== false) {
    $_SERVER['HTTPS']='on';
}

require_once ABSPATH . '../secrets.php';

// Sets up wordpress vars and included files.
require_once ABSPATH . 'wp-settings.php';
